### ISSUE TITLE
Run `update_wrds.sh` script

### ISSUE THREAD

**Issue by iangow** [mccgr/wrds_pg#54]
@bdcallen This will be a test of the documentation as much as anything. I think that if you run it on the Z640 machine not much will happen, as I ran it recently. I ran the CRSP part today (CRSP = US stock return data).

@dingtq If you wanted to try putting some WRDS data into a PostgreSQL server running on your computer, I think that could be quite feasible. 

```
igow@igow-z640:~/git/wrds_pg$ crsp/update_crsp.py 
crsp.tfz_idx already up to date
crsp.tfz_dly_ft already up to date
crsp.mse already up to date
crsp.msf already up to date
crsp.msi already up to date
crsp.msedelist already up to date
crsp.mport1 already up to date
crsp.dsf already up to date
Updated crsp.dsi is available.
Getting from WRDS.

Beginning file import at 20:24:58.
Importing data into crsp.dsi
Completed file import at 20:25:05.
Running SQL in crsp/make_trading_dates.sql

Running SQL: DROP TABLE IF EXISTS crsp.trading_dates CASCADE;
DROP TABLE

Running SQL: CREATE TABLE crsp.trading_dates AS
SELECT date, (rank() OVER (ORDER BY date))::integer AS td
    FROM (SELECT DISTINCT DATE FROM crsp.dsi) AS a;
SELECT 24793

Running SQL: CREATE INDEX ON crsp.trading_dates (date);
CREATE INDEX

Running SQL: CREATE INDEX trading_dates_td_idx ON crsp.trading_dates (td);
CREATE INDEX

Running SQL: CLUSTER crsp.trading_dates USING trading_dates_td_idx;
CLUSTER

Running SQL: ANALYZE crsp.trading_dates;
ANALYZE

Running SQL: ALTER TABLE crsp.trading_dates OWNER TO crsp;
ALTER TABLE

Running SQL: GRANT SELECT ON TABLE crsp.trading_dates TO crsp_access;
GRANT

Running SQL: DROP VIEW IF EXISTS crsp.all_dates;
DROP VIEW

Running SQL: CREATE VIEW crsp.all_dates AS
SELECT anncdate::date
FROM generate_series((SELECT min(date) FROM crsp.trading_dates)::timestamp,
		(SELECT max(date) FROM crsp.trading_dates), '1 day') AS anncdate;
CREATE VIEW

Running SQL: ALTER TABLE crsp.all_dates OWNER TO crsp;
ALTER TABLE

Running SQL: GRANT SELECT ON TABLE crsp.all_dates TO crsp_access;
GRANT

Running SQL: DROP TABLE IF EXISTS crsp.anncdates;
DROP TABLE

Running SQL: CREATE TABLE crsp.anncdates AS
SELECT a.anncdate, min(td) OVER w AS td, min(date) OVER w AS date
FROM crsp.all_dates AS a
LEFT JOIN crsp.trading_dates AS b
ON b.date = a.anncdate
WINDOW w AS (ORDER BY anncdate ROWS BETWEEN CURRENT ROW AND 7 FOLLOWING)
ORDER BY anncdate;
SELECT 34334

Running SQL: CREATE INDEX anncdates_anncdate_idx ON crsp.anncdates (anncdate);
CREATE INDEX

Running SQL: CLUSTER crsp.anncdates USING anncdates_anncdate_idx;
CLUSTER

Running SQL: ANALYZE crsp.anncdates;
ANALYZE

Running SQL: CREATE INDEX ON crsp.anncdates (anncdate);
CREATE INDEX

Running SQL: ALTER TABLE crsp.anncdates OWNER TO crsp;
ALTER TABLE

Running SQL: GRANT SELECT ON TABLE crsp.anncdates TO crsp_access;
GRANT
crsp.dsedelist already up to date
crsp.dport1 already up to date
Running SQL in crsp/crsp_make_rets_alt.sql

Running SQL: -- Create a table that integrates basic returns with delisting returns
SET work_mem='1999MB';
SET

Running SQL: DROP TABLE IF EXISTS crsp.rets;
DROP TABLE

Running SQL: CREATE TABLE crsp.rets AS
    WITH
    dsedelist AS (
        SELECT permno, dlstdt AS date, dlret
        FROM crsp.dsedelist),

    dsf_plus AS (
        SELECT permno, date,
            coalesce(1+a.ret,1) * coalesce(1+b.dlret,1)-1 AS ret
        FROM crsp.dsf AS a
        FULL OUTER JOIN dsedelist AS b
        USING (permno, date)
        WHERE a.ret IS NOT NULL OR b.dlret IS NOT NULL),

    dsf_w_erdport AS (
        SELECT a.*, b.decret
        FROM dsf_plus AS a
        LEFT JOIN crsp.erdport1 AS b
        USING (permno, date))

    SELECT c.*, d.vwretd
    FROM dsf_w_erdport AS c
    LEFT JOIN crsp.dsi AS d
    USING (date);
SELECT 94530552

Running SQL: ANALYZE crsp.rets;
ANALYZE

Running SQL: RESET work_mem;
RESET

Running SQL: -- Create indexes on PERMNO and DATE
SET maintenance_work_mem='1999MB';
SET

Running SQL: CREATE INDEX ON crsp.rets (permno);
CREATE INDEX

Running SQL: CREATE INDEX ON crsp.rets (date);
CREATE INDEX
crsp.ccmxpf_linktable already up to date
crsp.ccmxpf_lnkhist already up to date
crsp.dsedist already up to date
crsp.stocknames already up to date
crsp.dseexchdates already up to date
crsp.msp500list already up to date
crsp.ccmxpf_lnkused already up to date
crsp.dsp500 already up to date
crsp.dsp500p already up to date
crsp.msp500 already up to date
crsp.msp500p already up to date
crsp.mcti already up to date
crsp.mcti_corr already up to date
crsp.msedist already up to date
crsp.mseshares already up to date
```

**Comment by dingtq** [comment]
Thank you, @iangow! I will try it out sometime later. I guess I will first need to learn how to set up a PG server on my windows. :)

**Comment by iangow** [comment]
Point-and-click installers can be found [here](https://www.postgresql.org/download/windows/).

**Comment by bdcallen** [comment]
@iangow I git cloned `wrds_pg` and `wrds2pg`, but the script didn't run. So I did a pip install of wrds2pg and then ran the script, and here's what I got
```
bdcallen@igow-z640:~$ pip install wrds2pg
Collecting wrds2pg
  Downloading https://files.pythonhosted.org/packages/4a/52/d9134119b39cf9e939e7cc5ab1317627406af4229fcbdf1085df366e01b4/wrds2pg-0.1.22-py3-none-any.whl
Collecting paramiko (from wrds2pg)
  Downloading https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl (206kB)
     |████████████████████████████████| 215kB 8.7MB/s
Requirement already satisfied: sqlalchemy in ./anaconda3/lib/python3.7/site-packages (from wrds2pg) (1.2.15)
Requirement already satisfied: psycopg2 in ./anaconda3/lib/python3.7/site-packages (from wrds2pg) (2.7.7)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.7/site-packages (from wrds2pg) (0.23.4)
Collecting pynacl>=1.0.1 (from paramiko->wrds2pg)
  Downloading https://files.pythonhosted.org/packages/27/15/2cd0a203f318c2240b42cd9dd13c931ddd61067809fee3479f44f086103e/PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759kB)
     |████████████████████████████████| 768kB 32.3MB/s
Collecting bcrypt>=3.1.3 (from paramiko->wrds2pg)
  Downloading https://files.pythonhosted.org/packages/8b/1d/82826443777dd4a624e38a08957b975e75df859b381ae302cfd7a30783ed/bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl (56kB)
     |████████████████████████████████| 61kB 35.5MB/s
Collecting cryptography>=2.5 (from paramiko->wrds2pg)
  Downloading https://files.pythonhosted.org/packages/3c/04/686efee2dcdd25aecf357992e7d9362f443eb182ecd623f882bc9f7a6bba/cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7MB)
     |████████████████████████████████| 2.7MB 25.4MB/s
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.7/site-packages (from pandas->wrds2pg) (2.7.5)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.7/site-packages (from pandas->wrds2pg) (2018.7)
Requirement already satisfied: numpy>=1.9.0 in ./anaconda3/lib/python3.7/site-packages (from pandas->wrds2pg) (1.15.4)
Requirement already satisfied: cffi>=1.4.1 in ./anaconda3/lib/python3.7/site-packages (from pynacl>=1.0.1->paramiko->wrds2pg) (1.11.5)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from pynacl>=1.0.1->paramiko->wrds2pg) (1.12.0)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.7/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko->wrds2pg) (2.19)
Installing collected packages: pynacl, bcrypt, cryptography, paramiko, wrds2pg
  Found existing installation: cryptography 2.4.2
    Uninstalling cryptography-2.4.2:
      Successfully uninstalled cryptography-2.4.2
Successfully installed bcrypt-3.1.7 cryptography-2.9.2 paramiko-2.7.1 pynacl-1.3.0 wrds2pg-0.1.22

bdcallen@igow-z640:~/wrds_pg$ ./update_wrds.sh
Updating Audit Analytics (audit) ...
audit.feed41_transfer_agents already up to date
audit.auditnonreli already up to date
audit.feed09tocat already up to date
audit.feed09period already up to date
audit.feed09filing already up to date
audit.feed09cat already up to date
audit.feed25person already up to date
audit.namesauditorsinfo already up to date
audit.nt already up to date
audit.nt_part4_3_text already up to date
audit.bankrupt already up to date
audit.diroffichange already up to date
audit.feed17change already up to date
audit.feed17del already up to date
audit.sholderact already up to date
audit.feed13cat already up to date
audit.feed14case already up to date
audit.feed14party already up to date
audit.auditchange already up to date
audit.auditsox404 already up to date
audit.sox404_auditors already up to date
audit.sox404_event_auditors already up to date
audit.auditsox302 already up to date
audit.auditlegal already up to date

Updating Capital IQ (ciq) ...
ciq.wrds_gvkey already up to date
ciq.wrds_cusip already up to date
ciq.wrds_cik already up to date
ciq.ciqfininstance already up to date
ciq.ciqfinperiod already up to date
ciq.ciqgvkeyiid already up to date

Updating CRSP (crsp) ...
crsp.tfz_idx already up to date
crsp.tfz_dly_ft already up to date
crsp.mse already up to date
crsp.msf already up to date
crsp.msi already up to date
crsp.msedelist already up to date
crsp.mport1 already up to date
crsp.dsf already up to date
crsp.dsi already up to date
crsp.dsedelist already up to date
crsp.dport1 already up to date
crsp.ccmxpf_linktable already up to date
crsp.ccmxpf_lnkhist already up to date
crsp.dsedist already up to date
crsp.stocknames already up to date
crsp.dseexchdates already up to date
crsp.msp500list already up to date
crsp.ccmxpf_lnkused already up to date
crsp.dsp500 already up to date
crsp.dsp500p already up to date
crsp.msp500 already up to date
crsp.msp500p already up to date
crsp.mcti already up to date
crsp.mcti_corr already up to date
crsp.msedist already up to date
crsp.mseshares already up to date

Updating DealScan (dealscan) ...
dealscan.borrowerbase already up to date
dealscan.company already up to date
dealscan.currfacpricing already up to date
dealscan.dealamendment already up to date
dealscan.dealpurposecomment already up to date
dealscan.facility already up to date
dealscan.facilityamendment already up to date
dealscan.facilitydates already up to date
dealscan.facilityguarantor already up to date
dealscan.facilitypaymentschedule already up to date
dealscan.facilitysecurity already up to date
dealscan.facilitysponsor already up to date
dealscan.financialcovenant already up to date
dealscan.financialratios already up to date
dealscan.lendershares already up to date
dealscan.link_table already up to date
dealscan.lins already up to date
dealscan.marketsegment already up to date
dealscan.networthcovenant already up to date
dealscan.organizationtype already up to date
dealscan.package already up to date
dealscan.packageassignmentcomment already up to date
dealscan.performancepricing already up to date
dealscan.performancepricingcomments already up to date
dealscan.sublimits already up to date
dealscan.dbo_df_fac_dates_data already up to date

Updating IBES (ibes) ...
ibes.act_epsus already up to date
ibes.actpsumu_epsus already up to date
ibes.actu_epsus already up to date
ibes.detu_epsus already up to date
ibes.det_xepsus already up to date
ibes.curr already up to date
ibes.det_epsus already up to date
ibes.detu_epsint already up to date
ibes.id already up to date
ibes.idsum already up to date
ibes.surpsum already up to date
ibes.statsum_epsus already up to date
ibes.statsumu_epsus already up to date
ibes.det_guidance already up to date
ibes.det_guidance_ext already up to date
ibes.id_guidance already up to date
ibes.split_guidance already up to date
ibes.stop_epsus already up to date
ibes.exc_epsus already up to date
ibes.actpsum_epsus already up to date
Error in df_parse_dta_file(spec, encoding, cols_skip, n_max, skip, name_repair = .name_repair) :
  Failed to parse /tmp/Rtmpc4EwAR/file7aff7e48572f: Unable to read from file.
Calls: system.time ... %>% -> eval -> eval -> read_dta -> df_parse_dta_file
Timing stopped at: 0.047 0.014 0.064
Execution halted

Updating KLD (kld) ...
Getting new data
kld.history already up to date
kld.kldnames already up to date
Creating 'long' data table.
10.101.13.99

Updating MFLINKS (mflinks) ...
mfl.mflink1 already up to date
mfl.mflink2 already up to date

Updating RavenPack (rpna) ...
rpna.rp_entity_mapping already up to date
rpna.pr_equities_2000 already up to date
rpna.pr_equities_2001 already up to date
rpna.pr_equities_2002 already up to date
rpna.pr_equities_2003 already up to date
rpna.pr_equities_2004 already up to date
rpna.pr_equities_2005 already up to date
rpna.pr_equities_2006 already up to date
rpna.pr_equities_2007 already up to date
rpna.pr_equities_2008 already up to date
rpna.pr_equities_2009 already up to date
rpna.pr_equities_2010 already up to date
rpna.pr_equities_2011 already up to date
rpna.pr_equities_2012 already up to date
rpna.pr_equities_2013 already up to date
rpna.pr_equities_2014 already up to date
rpna.pr_equities_2015 already up to date
rpna.pr_equities_2016 already up to date
rpna.pr_equities_2017 already up to date
rpna.pr_equities_2018 already up to date
rpna.pr_equities_2019 already up to date
rpna.pr_equities_2020 already up to date

Updating Thomson Reuters (tfn) ...
tfn.amend already up to date
tfn.avgreturns already up to date
tfn.company already up to date
tfn.form144 already up to date
tfn.header already up to date
tfn.idfhist already up to date
tfn.idfnames already up to date
tfn.rule10b5 already up to date
tfn.table1 already up to date
tfn.table2 already up to date
tfn.s12type1 already up to date
tfn.s12type2 already up to date
tfn.s34 already up to date
tfn.s34type1 already up to date
tfn.s34type2 already up to date

Updating WRDS SEC Analytics (wrdssec) ...
wrdssec.wciklink_gvkey already up to date
wrdssec.wciklink_names already up to date
wrdssec.wciklink_cusip already up to date
``` 

As you suggested, not much happened, as you did an update earlier. Though there was an "unable to read from file" error. Is this an issue?

**Comment by iangow** [comment]
You might want to dig a bit deeper into the following. You could just run the `ibes/update_ibes.py` script or even the lines that seem to be causing the problem.

```
ibes.actpsum_epsus already up to date
Error in df_parse_dta_file(spec, encoding, cols_skip, n_max, skip, name_repair = .name_repair) :
  Failed to parse /tmp/Rtmpc4EwAR/file7aff7e48572f: Unable to read from file.
Calls: system.time ... %>% -> eval -> eval -> read_dta -> df_parse_dta_file
Timing stopped at: 0.047 0.014 0.064
Execution halted
```

**Comment by iangow** [comment]
Note that the issue above appears to be one in R. Not much in the code uses R. So must be a special script requirement.

**Comment by bdcallen** [comment]
@iangow 

```
bdcallen@igow-z640:~/wrds_pg$ export WRDS_ID="bdcallen"
bdcallen@igow-z640:~/wrds_pg$ python3 ibes/update_ibes.py
Traceback (most recent call last):
  File "ibes/update_ibes.py", line 7, in <module>
    wrds_update("act_epsus", "ibes")
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/wrds2pg/wrds2pg.py", line 435, in wrds_update
    modified = get_modified_str(table_name, schema, wrds_id, encoding=encoding)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/wrds2pg/wrds2pg.py", line 300, in get_modified_str
    p = get_process(sas_code, wrds_id)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/wrds2pg/wrds2pg.py", line 27, in get_process
    username=wrds_id, compress=True)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/paramiko/client.py", line 416, in connect
    self, server_hostkey_name, server_key
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/paramiko/client.py", line 824, in missing_host_key
    "Server {!r} not found in known_hosts".format(hostname)
paramiko.ssh_exception.SSHException: Server 'wrds-cloud.wharton.upenn.edu' not found in known_hosts
```

Looking back at the documentation, it seems I've skipped the part of step 2 in setting up the RSA key.

Is there an env

**Comment by iangow** [comment]
How did it work the first time, I wonder?

Just follow the instructions [here](https://github.com/iangow/wrds2pg). You can put `WRDS_ID` in your `.profile`.

**Comment by bdcallen** [comment]
@iangow So I need a `.ssh` directory on Z-640? Or just on the wrds server? I'm confused, as I'm getting some errors. 

```
bdcallen@igow-z640:~/wrds_pg$ ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/home/bdcallen/.ssh/id_rsa): cat ~/.ssh/id_rsa.pub | ssh bdcallen@wrds-cloud.wharton.upenn.edu "cat >> ~/.ssh/authorized_keys"
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Saving key "cat ~/.ssh/id_rsa.pub | ssh bdcallen@wrds-cloud.wharton.upenn.edu "cat >> ~/.ssh/authorized_keys"" failed: No such file or directory
```

Also, doing an ssh into the wrds server, and then doing mkdir '/.ssh', I got this

```
[bdcallen@wrds-cloud-login2-w ~]$ mkdir ~/.ssh
mkdir: cannot create directory ‘/home/unimelb/bdcallen/.ssh’: File exists
```

**Comment by iangow** [comment]
On both. Is `.ssh` a directory on the WRDS server? You might want to run `cat ~/.ssh/id_rsa.pub` to check where you're having the problem.

**Comment by bdcallen** [comment]
Seems it already exists on both for me

```
bdcallen@igow-z640:~$ mkdir ~/.ssh
mkdir: cannot create directory ‘/home/bdcallen/.ssh’: File exists
```

I'll give the command you suggested a go

**Comment by iangow** [comment]
`File exists`, but is it a directory?

**Comment by bdcallen** [comment]
Yes

```
bdcallen@igow-z640:~$ cd /home/bdcallen/.ssh
bdcallen@igow-z640:~/.ssh$ ls
id_rsa  id_rsa.pub  known_hosts
```

**Comment by iangow** [comment]
BTW, the R installation on the Z640 was a bit of a mess. So I reinstalled it (hopefully after you were done for the evening). I think it should all be there now, you may want to restart your R session (if any), as it's now R 4.0.0.

**Comment by iangow** [comment]
@bdcallen Once you work out what was causing the issue (in R) above, you can close this issue.

**Comment by iangow** [comment]
@bdcallen Any updates on this?

**Comment by bdcallen** [comment]
@iangow So after I just did the successful generation of the rsa key at the end of the meeting, I got an rsa key in `id_rsa.pub` attached to `bdcallen@igow-z640`. Then did 

```
bdcallen@igow-z640:~/.ssh$ cat ~/.ssh/id_rsa.pub | ssh bdcallen@wrds-cloud.wharton.upenn.edu "cat >> ~/.ssh/authorized_keys"
bdcallen@wrds-cloud.wharton.upenn.edu's password:
ssh bdcallen@wrds-cloud.wharton.upenn.edu
[bdcallen@wrds-cloud-login2-w ~]$ cd ~/.ssh
[bdcallen@wrds-cloud-login2-w .ssh]$ ls
authorized_keys  id_rsa  id_rsa.pub
[bdcallen@wrds-cloud-login2-w .ssh]$ cat authorized_keys
```

I then tried running the script and got

```
bdcallen@igow-z640:~/wrds_pg$ ./update_wrds.sh
Updating Audit Analytics (audit) ...
Traceback (most recent call last):
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 342, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/bdcallen/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection timed out
        Is the server running on host "10.101.99.13" and accepting
        TCP/IP connections on port 5432?

```

At the moment the program is still running, but is giving me the same error for the other tables. Which I find bemusing, since I have set up all the environmental variables, PGHOST, PGDATABASE, PGUSER, PGPASSWORD and WRDS_ID. So I have no idea why it's not connecting to the server.

**Comment by bdcallen** [comment]
@iangow 

```
bdcallen@igow-z640:~/wrds_pg$ printenv PGHOST
localhost
bdcallen@igow-z640:~/wrds_pg$ ./update_wrds.sh
Updating Audit Analytics (audit) ...
audit.feed41_transfer_agents already up to date
audit.auditnonreli already up to date
audit.feed09tocat already up to date
audit.feed09period already up to date
audit.feed09filing already up to date
audit.feed09cat already up to date
...
````
I had PGHOST set to the IP address, not localhost. Doing that has fixed the problem, and now the program is running

**Comment by iangow** [comment]
Having `PGHOST` set to `10.101.13.99` should be fine except for the absence of a corresponding entry in your `~/.pgpass` file. This would be easy to add.

**Comment by bdcallen** [comment]
@iangow 

```
bdcallen@igow-z640:~/wrds_pg$ ./update_wrds.sh
Updating Audit Analytics (audit) ...
audit.feed41_transfer_agents already up to date
audit.auditnonreli already up to date
audit.feed09tocat already up to date
audit.feed09period already up to date
audit.feed09filing already up to date
audit.feed09cat already up to date
audit.feed25person already up to date
audit.namesauditorsinfo already up to date
audit.nt already up to date
audit.nt_part4_3_text already up to date
audit.bankrupt already up to date
audit.diroffichange already up to date
audit.feed17change already up to date
audit.feed17del already up to date
audit.sholderact already up to date
audit.feed13cat already up to date
audit.feed14case already up to date
audit.feed14party already up to date
audit.auditchange already up to date
audit.auditsox404 already up to date
audit.sox404_auditors already up to date
audit.sox404_event_auditors already up to date
audit.auditsox302 already up to date
audit.auditlegal already up to date

Updating Capital IQ (ciq) ...
ciq.wrds_gvkey already up to date
ciq.wrds_cusip already up to date
ciq.wrds_cik already up to date
ciq.ciqfininstance already up to date
ciq.ciqfinperiod already up to date
ciq.ciqgvkeyiid already up to date

Updating CRSP (crsp) ...
crsp.tfz_idx already up to date
crsp.tfz_dly_ft already up to date
crsp.mse already up to date
crsp.msf already up to date
crsp.msi already up to date
crsp.msedelist already up to date
crsp.mport1 already up to date
crsp.dsf already up to date
crsp.dsi already up to date
crsp.dsedelist already up to date
crsp.dport1 already up to date
crsp.ccmxpf_linktable already up to date
crsp.ccmxpf_lnkhist already up to date
crsp.dsedist already up to date
crsp.stocknames already up to date
crsp.dseexchdates already up to date
crsp.msp500list already up to date
crsp.ccmxpf_lnkused already up to date
crsp.dsp500 already up to date
crsp.dsp500p already up to date
crsp.msp500 already up to date
crsp.msp500p already up to date
crsp.mcti already up to date
crsp.mcti_corr already up to date
crsp.msedist already up to date
crsp.mseshares already up to date

Updating DealScan (dealscan) ...
dealscan.borrowerbase already up to date
dealscan.company already up to date
dealscan.currfacpricing already up to date
dealscan.dealamendment already up to date
dealscan.dealpurposecomment already up to date
dealscan.facility already up to date
dealscan.facilityamendment already up to date
dealscan.facilitydates already up to date
dealscan.facilityguarantor already up to date
dealscan.facilitypaymentschedule already up to date
dealscan.facilitysecurity already up to date
dealscan.facilitysponsor already up to date
dealscan.financialcovenant already up to date
dealscan.financialratios already up to date
dealscan.lendershares already up to date
dealscan.link_table already up to date
dealscan.lins already up to date
dealscan.marketsegment already up to date
dealscan.networthcovenant already up to date
dealscan.organizationtype already up to date
dealscan.package already up to date
dealscan.packageassignmentcomment already up to date
dealscan.performancepricing already up to date
dealscan.performancepricingcomments already up to date
dealscan.sublimits already up to date
dealscan.dbo_df_fac_dates_data already up to date

Updating IBES (ibes) ...
ibes.act_epsus already up to date
ibes.actpsumu_epsus already up to date
ibes.actu_epsus already up to date
ibes.detu_epsus already up to date
ibes.det_xepsus already up to date
ibes.curr already up to date
ibes.det_epsus already up to date
ibes.detu_epsint already up to date
ibes.id already up to date
ibes.idsum already up to date
ibes.surpsum already up to date
ibes.statsum_epsus already up to date
ibes.statsumu_epsus already up to date
ibes.det_guidance already up to date
ibes.det_guidance_ext already up to date
ibes.id_guidance already up to date
ibes.split_guidance already up to date
ibes.stop_epsus already up to date
ibes.exc_epsus already up to date
ibes.actpsum_epsus already up to date
   user  system elapsed 
  0.172   0.059   9.352 

Updating KLD (kld) ...
Getting new data
kld.history already up to date
kld.kldnames already up to date
Creating 'long' data table.
localhost

Updating MFLINKS (mflinks) ...
WRDS flaked out!
mfl.mflink2 already up to date

Updating RavenPack (rpna) ...
rpna.rp_entity_mapping already up to date
rpna.pr_equities_2000 already up to date
rpna.pr_equities_2001 already up to date
rpna.pr_equities_2002 already up to date
rpna.pr_equities_2003 already up to date
rpna.pr_equities_2004 already up to date
rpna.pr_equities_2005 already up to date
rpna.pr_equities_2006 already up to date
rpna.pr_equities_2007 already up to date
rpna.pr_equities_2008 already up to date
rpna.pr_equities_2009 already up to date
rpna.pr_equities_2010 already up to date
rpna.pr_equities_2011 already up to date
rpna.pr_equities_2012 already up to date
rpna.pr_equities_2013 already up to date
rpna.pr_equities_2014 already up to date
rpna.pr_equities_2015 already up to date
rpna.pr_equities_2016 already up to date
rpna.pr_equities_2017 already up to date
rpna.pr_equities_2018 already up to date
rpna.pr_equities_2019 already up to date
rpna.pr_equities_2020 already up to date

Updating Thomson Reuters (tfn) ...
tfn.amend already up to date
tfn.avgreturns already up to date
tfn.company already up to date
tfn.form144 already up to date
tfn.header already up to date
tfn.idfhist already up to date
tfn.idfnames already up to date
tfn.rule10b5 already up to date
tfn.table1 already up to date
tfn.table2 already up to date
tfn.s12type1 already up to date
tfn.s12type2 already up to date
tfn.s34 already up to date
tfn.s34type1 already up to date
tfn.s34type2 already up to date

Updating WRDS SEC Analytics (wrdssec) ...
WRDS flaked out!
WRDS flaked out!
WRDS flaked out!
```

So I have run the program. What does `WRDS flaked out!` mean? If this is not a big deal, I think we can close.

**Comment by iangow** [comment]
Close enough for now (I'm seeing the same error message).
